# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataBelongsArea',
            new_name='DataIntoAreaRelation',
        ),
    ]
