# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170927_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystreamentry',
            name='target_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activitystreamentry',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_stream_entry_as_target_type', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='child',
            name='educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Educator'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='dataintoarearelation',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
        ),
    ]
